### PR TITLE
Boilerplate website

### LINKED ISSUE #26: Develop React Boilerplate Website
Currently the boilerplate has a very naive website : http://react-simple-boilerplate.surge.sh/

Add all the components and proper documentation in the website with proper SEO.

### PR DESCRIPTION
**Pull request by mundane140**
Resolves #26 

### Checklist

- [x] Initialize project using create-next-app in `/website` directory
- [x] Add home page and its components
- [x] Add Docs page and its components

### CODE REVIEW

**Comment by mundane140** [comment]
@udaypydi I had to delete the /website/.next folder and add it to .gitignore.

**Comment by udaypydi** [comment]
@mundane140 any updates?

**Comment by mundane140** [comment]
Here is what I have at the moment. I need to know more about how you are planning on saving docs. I have added the necessary code for getting docs from markdown files saved in the `docs` directory.

**Comment by mundane140** [comment]
@udaypydi requesting review.
I have completed docs as well. 
You need to place all the markdown files in the /docs directory. See any doc file for format. 
The navigation is similar to that used on CRA docs. 
Lemme know if you need anything else.

**Comment by udaypydi** [comment]
> @udaypydi requesting review.
> I have completed docs as well. 
> You need to place all the markdown files in the /docs directory. See any doc file for format. 
> The navigation is similar to that used on CRA docs. 
> Lemme know if you need anything else.

Awesome. Thanks! I will review it tonight.

**Comment by mundane140** [comment]
I might have messed up the branch while trying to pull changes from master. 😅
My changes are till commit: [e2b8bb5](https://github.com/udaypydi/react-simple-boilerplate/pull/59/commits/e2b8bb59385aea6068c1a54e0ddbfa36999cfe29).

**Comment by mundane140** [comment]
Closing this and opening a new PR with all the changes.

**Pull request closed without merging**
