### PR TITLE
React website

### PR DESCRIPTION
**Pull request by udaypydi**

### CODE REVIEW

**Comment by akshay-nm** [comment]
@udaypydi did you checkout [docusaurus](https://v2.docusaurus.io/)? 
This is what CRA uses for docs. I know I have worked a lot on the docs but don't feel any obligation to merge it if you have not already. Check this out first. 😅

**Comment by udaypydi** [comment]
@akshay-nm this looks great. Will be happy to merge if you don't mind adding this.

**Comment by akshay-nm** [comment]
where to branch out from?

**Comment by akshay-nm** [comment]
@udaypydi I have checked out from this branch and added the docusaurus version of website as a separate package.

#90

**Pull request closed without merging**
